---
name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix

      # validate templates
      # - name: Validate Template
      #  uses: hashicorp/packer-github-actions@master
      #  with:
      #    command: validate
      #    arguments: -syntax-only
      #    target: packer.pkr.hcl

      # validate templates
      - name: Packer Validate
        uses: ./
        with:
          command: packer validate -syntax-only app.json
          working_directory: ./packer

      # validate templates
      - name: Packer Validate
        uses: ./
        with:
          command: packer validate -syntax-only db.json
          working_directory: ./packer
